### ISSUE TITLE
Expose stream api (NotificationCallback, FollowedCallback, etc)

### ISSUE THREAD

**Issue by MawsFr** [uakihir0/misskey4j#23]
Hello ^^

I see that streaming API for every type of event (NotificationCallback, FollowedCallback, RenoteCallback, ReplayCallback, etc) are present in the StreamClient class but not exposed in the MisskeyStream under the stream() function.

Could you expose these APIs please ^^ ?

Thank you in advance

EDIT : Should we be able to pass a callback to the "main" stream() ?

**Comment by MawsFr** [comment]
Okay I just understood how to use the main stream

Maybe you could provide a more detailed documentation on stream ^^ ?

```java
try {
            Misskey misskey = MisskeyFactory.getInstanceWithOwnedAccessToken(getHost(), user.socialNetworkInfos().orElseThrow().token());
            MisskeyStream stream = misskey.stream();
            stream.setOpenedCallback(() -> {
                System.out.println("Stream opened");
                stream.main((NotificationCallback) notification -> System.out.println("Notification received"));
                stream.main((FollowedCallback) follow -> System.out.println("Follow received"));

                stream.globalTimeline(note -> {
                    this.router.onNewPost(user.id(), SocialNetworkEvent.NEW_POST_ON_FEED, toPost(note));
                });
            });

            stream.setClosedCallback((remote) -> {
                System.out.println("Stream closed " + remote);
            });

            stream.setErrorCallback((error) -> {
                try {
                    throw error;
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            });
            stream.connect();

        } catch (RuntimeException ex) {
            throw new SocialNetworkClientException(ex);
        }
```

**Comment by uakihir0** [comment]
This is a bit of a crude guide, but I hope you can see the test code.
https://github.com/uakihir0/misskey4j/blob/master/src/test/java/misskey4j/apis/StreamTest.java

**Comment by MawsFr** [comment]
Yeah thank you I saw it later ^^

**Comment by MawsFr** [comment]
Hello :)

I used the stream API but I noticed that there are a missing messages that are note implemented yet in particular these  (reacted, note deleted etc): https://misskey-hub.net/en/docs/api/streaming/note-capture-events.html

Do you plan to implement them ?

Thanks ^^

**Comment by MawsFr** [comment]
To be more explicit, I see in your code that you catch only events of type "channel" but misskey also sends other types of events like "noteUpdated" which corresponds to events on a single note (reacted, deleted, etc)

<img width="783" alt="Capture d’écran 2023-09-03 à 20 29 28" src="https://github.com/uakihir0/misskey4j/assets/4595534/700f28b1-ba4d-47c7-9b9f-96756b1858e7">

**Comment by MawsFr** [comment]
I made a PR if you want to review it ^^
